export const TableNames = {
	checkouts :"checkouts",
	checkIns :"checkins",
	checkoutQrs :"checkout_qrs",
	checkInQrs :"checkin_qrs",
	qrLocations :"qr_locations",
	supplyBeamLocations:"supply_beam_locations",
	qr :"qr",
	returningQrs :"returning_qrs",
	pickLists :"pick_lists",
	pickListItems :"picklist_items",
	pickListQrCodes :"picklist_qrcodes",
	orders :"orders",
	orderItems :"order_items",
};
